---
- name: Client Side Auto-Setup
  hosts: localhost
  connection: local
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install Podman and Avahi
      zypper:
        name: [podman, avahi, nss-mdns]
        state: present

    - name: Ensure Avahi is running (mDNS)
      service:
        name: avahi-daemon
        state: started
        enabled: yes

    - name: Deploy Backend Container
      containers.podman.podman_container:
        name: rungard-backend
        image: ghcr.io/agneswd/test-backend:v1.0
        state: started
        label:
          io.containers.autoupdate: registry
